sudo: required
services:
  - docker

before_install:
  - docker build -t laurentagarini/docker-react -f Dockerfile.dev .

script:
  - docker run  laurentagarini/docker-react npm run test -- --coverage
